import { Inter } from "next/font/google";
import "./globals.css";
import Porvider from "@/redux/provider/Porvider";
import { MainContextProvider } from "@/Context/UseFilter";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const getData1 = async () => {
  const res = await fetch("https://fakestoreapi.com/products");

  const data = res.json();

  return data;
};

export default function RootLayout({ children }) {
  let data1 = getData1();
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainContextProvider>
          <Porvider>{children}</Porvider>
        </MainContextProvider>
      </body>
    </html>
  );
}
